#!/bin/zsh
. ./.env
echo $DEBUG
node \
  --env-file=.env \
  --experimental-sqlite \
  src/index.js | \
 # jq --unbuffered --arg  DEBUG "$DEBUG" '.name as $name | select($DEBUG | contains($name))' |
  node ../../node_modules/.bin/pino-colada

# echo '{"name": "yah/parse"}' |
#  jq --arg DEBUG "$DEBUG" '.name as $name | select($DEBUG | contains($name))' |
#  node ../../node_modules/.bin/pino-colada
